spring:
  application:
    name: portal
  main:
    web-application-type: reactive
  webflux:
    static-path-pattern: /nonexistent/**  # 禁用默认静态资源路径
    base-path: /meal
  profiles:
    active: dev
  messages:
#    国际化文件
    basename: i18n/messages
    encoding: UTF-8
server:
  port: 8090
  servlet:
    context-path: /meal
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: GtOe3z3oHqKeEPa1qsUc
  secretKey: ztbAknufshRpZlkDqXz1bbOgjnD5zomsbQ77dbpO
  bucketName: meal-img-public
redisson:
  config:
    address: redis://127.0.0.1:6379
    password:  # 如果有密码
    database: 0
external-services:
  services:
    wechat:
      base_url: https://api.weixin.qq.com
      appid: wx64979d00d4753ae5
      secret: 35cc42dfdabfd937f0fc4c3049a65fd4
      connect-timeout: 5s
      read-timeout: 7s
      write-timeout: 6s
# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: sa-token-authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 3600
  # token风格
  token-style: random-32
  # 是否尝试从 header 里读取 Token
  is-read-head: true
  is-use-redis: true  # 必须显式开启Redis存储
  # 是否开启自动续签
  auto-renew: true
  # 临时有效期，单位s，例如将其配置为 1800 (30分钟)，代表用户如果30分钟无操作，则此Token会立即过期
  activity-timeout: 1800
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时同端互斥)
  is-concurrent: false
  # 配置 Sa-Token 单独使用的 Redis 连接

logging:
  level:
    cn.dev33.satoken: DEBUG  # 开启 Sa-Token 详细日志
    org.springframework.web.reactive: DEBUG
