spring:
  application:
    name: portal
  main:
    web-application-type: reactive
  webflux:
    static-path-pattern: /nonexistent/**  # 禁用默认静态资源路径
    base-path: /meal
  profiles:
    active: dev
  messages:
#    国际化文件
    basename: i18n/messages
    encoding: UTF-8
server:
  port: 8090
  servlet:
    context-path: /meal
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: GtOe3z3oHqKeEPa1qsUc
  secretKey: ztbAknufshRpZlkDqXz1bbOgjnD5zomsbQ77dbpO
  bucketName: meal-img-public
redisson:
  config:
    address: redis://127.0.0.1:6379
    password:  # 如果有密码
    database: 0
external-services:
  services:
    wechat:
      base_url: https://api.weixin.qq.com
      appid: wx64979d00d4753ae5
      secret: 35cc42dfdabfd937f0fc4c3049a65fd4
      connect-timeout: 5s
      read-timeout: 7s
      write-timeout: 6s
# Sa-Token配置
jwt:
  secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  expiration: 604800000
logging:
  level:
    cn.dev33.satoken: DEBUG  # 开启 Sa-Token 详细日志
    org.springframework.web.reactive: DEBUG
